### ISSUE TITLE
Not displaying correctly

### ISSUE THREAD

**Issue by natvilla** [EPICmynamesBG/brackets-csv-formatter#1]
Hi! Cool idea! I have just downloaded the extension and it is not displaying correctly for me. I am on a Mac. After some debugging, it looks like maybe the .cm-m-csv class is not getting added? If I look at the html after loading, it is showing the table elements as 
`<span class="cm-column cm-column-(index)">`.
In the debugger, I see that _currentColumns_ is empty, but it is working for me if I remove that part of the selector in __calculateColumnWidths_. I also had to change the css to _span.cm-column_ instead of _.cm-m-csv.cm-column_.

**Comment by EPICmynamesBG** [comment]
@natvilla Thanks for the feedback :+1: I'm bobbling a few side projects right now, but I can probably take a look at that this weekend. Alternatively, if you want to contribute, feel free to make a PR 😄

**Comment by natvilla** [comment]
Cool. Thanks! 
Also, I might be able to contribute, but probably wouldn't get to doing so until after the long weekend. :)

**Comment by EPICmynamesBG** [comment]
@natvilla If you can, check out PR #2 and pull that branch, let me know if that works for you. There's still some alignment quirks that I'm struggling to iron out, but it should be a lot better than it was. It looks like the `cm-m-csv` class was somehow being automatically added by a theme that I was using. I've modified the codemirror theming function to now include that class (regardless of theme), so things are styling. 

I also went ahead and made the table style solid lines :+1:

**Comment by natvilla** [comment]
Yes, it works for me now. But yes, there seem to be some alignment issues - not when I first open the file, but if I make any changes to the csv content.

**Comment by EPICmynamesBG** [comment]
@natvilla Ya, I haven't taken a deep dive into it yet. I'l go ahead and create another issue for display fine-tuning, but if you think this is acceptable as is for now, give this comment a :+1:, I'll go ahead and merge and close this one. Other feedback (whether it by styling or such) is welcome at this time as well and I can create some tasks for those 😃

**Comment by EPICmynamesBG** [comment]
Resolved via #2

**Comment by EPICmynamesBG** [comment]
Resolved via #2
