### ISSUE TITLE
Brackets ES6 

### ISSUE THREAD

**Issue by Wikunia** [EPICmynamesBG/brackets-csv-formatter#5]
Hi,

sorry maybe it's not your fault. I can't run this extension because you're using ES6 in your extension.
I'm not sure whether Brackets supports it and therefore is my error or if you are transpile it on your machine but only upload the ES6 version. If that's the case it would be nice if you would git the transpiled version.

**Comment by EPICmynamesBG** [comment]
Hmm, I would have thought that since Brackets is built on top of node, which doesn't require transpiling, it would be fine. Nevertheless, I'll look into it :+1:

**Comment by Wikunia** [comment]
I thought the same and if it works on your machine it isn't your fault I suppose.
Brackets behaves strange sometimes :D

**Comment by EPICmynamesBG** [comment]
@Wikunia if you could checkout https://github.com/EPICmynamesBG/brackets-csv-formatter/pull/6, maybe even pull that code and run that in your plugin, I think I've removed all ES6 syntax. Hopefully that works for you.

**Comment by EPICmynamesBG** [comment]
Resolved in #6
